CREATE OR REPLACE TYPE STRONA_TYP AS OBJECT(
    STRONA_ID NUMBER,
    TRESC VARCHAR(100),
    NUMER_STRONY NUMBER
); 

CREATE OR REPLACE TYPE STRONY_TAB AS TABLE OF STRONA;

CREATE OR REPLACE TYPE AUTOR_TYP AS OBJECT (
    AUTOR_ID NUMBER,
    IMIE VARCHAR(100),
    NAZWISKO VARCHAR(100)
);

CREATE OR REPLACE TYPE KSIAZKA_TYP AS OBJECT(
    KSIAZKA_ID NUMBER,
    TYTUL VARCHAR(50),
    STRONY STRONY_TAB,
    AUTOR REF AUTOR_TYP,
    SZAFKA REF SZAFKA_TYP
);

CREATE OR REPLACE TYPE SZAFKA_TYP AS OBJECT (
    SZAFKA_ID NUMBER,
    MAX_POJEMNOSC NUMBER
);