CREATE OR REPLACE TYPE STRONA_TYP AS OBJECT(
    STRONA_ID INT,
    TRESC VARCHAR(100),
    NUMER_STRONY NUMBER
); 

CREATE OR REPLACE TYPE STRONA_TAB AS TABLE OF STRONA_TYP;

CREATE OR REPLACE TYPE AUTOR_TYP AS OBJECT (
    AUTOR_ID INT,
    IMIE VARCHAR(100),
    NAZWISKO VARCHAR(100)
);

CREATE OR REPLACE TYPE SZAFKA_TYP AS OBJECT (
    SZAFKA_ID INT,
    MAX_POJEMNOSC NUMBER,
    AKTUALNA_LICZBA_KSIAZEK NUMBER
);

CREATE OR REPLACE TYPE KSIAZKA_TYP AS OBJECT(
    KSIAZKA_ID INT,
    TYTUL VARCHAR(50),
    STRONY STRONA_TAB,
    AUTOR REF AUTOR_TYP,
    SZAFKA REF SZAFKA_TYP
);
