CREATE SEQUENCE seq_ksiazka_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_autor_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_szafka_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_strona_id START WITH 1 INCREMENT BY 1;

CREATE TABLE KSIAZKA OF KSIAZKA_TYP(
    KSIAZKA_ID DEFAULT seq_ksiazka_id.NEXTVAL,
    CONSTRAINT PK_Ksiazka PRIMARY KEY (KSIAZKA_ID),
    CONSTRAINT unique_tytul UNIQUE (TYTUL)
)
NESTED TABLE STRONY STORE AS STRONY_nested_table; 

CREATE TABLE AUTOR OF AUTOR_TYP(
    AUTOR_ID DEFAULT seq_autor_id.NEXTVAL,
    CONSTRAINT PK_Autor PRIMARY KEY (AUTOR_ID),
    CONSTRAINT unique_autor UNIQUE (IMIE, NAZWISKO)
);

CREATE TABLE SZAFKA OF SZAFKA_TYP (
    SZAFKA_ID DEFAULT seq_szafka_id.NEXTVAL,
    CONSTRAINT PK_Szafka PRIMARY KEY (SZAFKA_ID)
);

-- TABELA CZYSTO RELACYJNA
CREATE TABLE GATUNEK (
    GATUNEK_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAZWA_GATUNKU VARCHAR(50),
    CONSTRAINT unique_GATUNEK UNIQUE (NAZWA_GATUNKU)
)

-- RELACJA WIELE DO WIELU MIEDZY KSIAZKAMI I GATUNKAMI
CREATE TABLE KSIAZKA_GATUNEK (
    KSIAZKA_ID INT,
    GATUNEK_ID INT,
    PRIMARY KEY (KSIAZKA_ID, GATUNEK_ID),
    CONSTRAINT FK_Ksiazka FOREIGN KEY (KSIAZKA_ID) REFERENCES KSIAZKA(KSIAZKA_ID),
    CONSTRAINT FK_Gatunek FOREIGN KEY (GATUNEK_ID) REFERENCES GATUNEK(GATUNEK_ID)
)

CREATE TABLE HISTORIA_PRZENOSIN (
    LOG_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KSIAZKA_ID INT,
    STARA_SZAFKA REF SZAFKA_TYP,
    NOWA_SZAFKA REF SZAFKA_TYP,
    DATA_ZMIANY DATE
);