CREATE TABLE KSIAZKA OF KSIAZKA_TYP(
    CONSTRAINT PK_Ksiazka PRIMARY KEY (KSIAZKA_ID)
)
NESTED TABLE STRONY STORE AS STRONY_nested_table; 

CREATE TABLE AUTOR OF AUTOR_TYP(
    CONSTRAINT PK_Autor PRIMARY KEY (AUTOR_ID)
);

CREATE TABLE SZAFKA OF SZAFKA_TYP (
    CONSTRAINT PK_Szafka PRIMARY KEY (SZAFKA_ID)
);

-- TABELA CZYSTO RELACYJNA
CREATE TABLE GATUNEK (
    GATUNEK_ID INT PRIMARY KEY,
    NAZWA_GATUNKU VARCHAR(50)
)

-- RELACJA WIELE DO WIELU MIEDZY KSIAZKAMI I GATUNKAMI
CREATE TABLE KSIAZKA_GATUNEK (
    KSIAZKA_ID INT,
    GATUNEK_ID INT,
    PRIMARY KEY (KSIAZKA_ID, GATUNEK_ID),
    CONSTRAINT FK_Ksiazka FOREIGN KEY (KSIAZKA_ID) REFERENCES KSIAZKA(KSIAZKA_ID),
    CONSTRAINT FK_Gatunek FOREIGN KEY (GATUNEK_ID) REFERENCES GATUNEK(GATUNEK_ID)
)