CREATE OR REPLACE TRIGGER TR_UjemnyNumerStrony
BEFORE INSERT OR UPDATE ON STRONY_nested_table
FOR EACH ROW
BEGIN
    IF :NEW.NUMER_STRONY <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Numer strony nie moze byc ujemny');
    END IF;
END;

CREATE OR REPLACE TRIGGER TR_MaxStron
BEFORE INSERT OR UPDATE ON KSIAZKA
FOR EACH ROW
BEGIN 
    IF :NEW.STRONY IS NOT NULL AND :NEW.STRONY.COUNT > 10 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ksiazka nie moze miec wiecej niz 10 stron');
    END IF;
END;

CREATE OR REPLACE TRIGGER TR_IloscKsiazekNaSzafce
BEFORE INSERT OR DELETE OR UPDATE OF SZAFKA ON KSIAZKA
FOR EACH ROW
DECLARE
    v_max NUMBER;
    v_aktualna NUMBER;
BEGIN
    IF (DELETING OR UPDATING) AND :OLD.SZAFKA IS NOT NULL THEN
        UPDATE SZAFKA s 
        SET AKTUALNA_LICZBA_KSIAZEK = AKTUALNA_LICZBA_KSIAZEK - 1
        WHERE REF(s) = :OLD.SZAFKA;
    END IF;

    IF (INSERTING OR UPDATING) AND :NEW.SZAFKA IS NOT NULL THEN
        SELECT MAX_POJEMNOSC, AKTUALNA_LICZBA_KSIAZEK 
        INTO v_max, v_aktualna
        FROM SZAFKA s 
        WHERE REF(s) = :NEW.SZAFKA;
        
        IF v_aktualna >= v_max THEN
            RAISE_APPLICATION_ERROR(-20004, 'Brak miejsca na tej szafce!');
        END IF;
        
        UPDATE SZAFKA s 
        SET AKTUALNA_LICZBA_KSIAZEK = AKTUALNA_LICZBA_KSIAZEK + 1
        WHERE REF(s) = :NEW.SZAFKA;
    END IF;
    
    IF UPDATING AND :OLD.SZAFKA IS NOT NULL THEN
        UPDATE SZAFKA s 
        SET AKTUALNA_LICZBA_KSIAZEK = AKTUALNA_LICZBA_KSIAZEK - 1
        WHERE REF(s) = :OLD.SZAFKA;
    END IF;
END;

CREATE OR REPLACE TRIGGER TR_AudytPrzenoszeniaKsiazki
AFTER UPDATE OF SZAFKA ON KSIAZKA
FOR EACH ROW
BEGIN
    INSERT INTO HISTORIA_PRZENOSIN (KSIAZKA_ID, STARA_SZAFKA, NOWA_SZAFKA, DATA_ZMIANY)
    VALUES (:NEW.KSIAZKA_ID, :OLD.SZAFKA, :NEW.SZAFKA, SYSDATE);
END;
